- name: get secrets
  hosts: localhost
  tasks:
    - name: get vault secrets
      ansible.builtin.lineinfile:
        path: ~/secrets.json
        line: "Username: {{ lookup('hashi_vault', 'secret=common/data/vault_secrets token=$vault_token url=https://3.81.88.227:8200 validate_certs=False') }}"
        create: yes

