- name: get secrets
  hosts: localhost
  tasks:
    - name: get vault secrets
      ansible.builtin.lineinfile:
        path: ~/secrets.json
        line: "Username: {{ lookup('hashi_vault', 'secret=common/data/secrets_ token=$vault_token url=https://vault.pdevops72.online:8200') }}"
        create: yes

