- name: get secrets
  hosts: localhost
  tasks:
    - name: get vault secrets
      ansible.builtin.lineinfile:
        path: ~/secrets.json
        line: "{{ lookup('hashi_vault', 'secret=common/data/vault_secrets  token={{vault_token}} url=https://vault-internal.pdevops72.online:8200 validate_certs=False')}}"
        create: yes

    - name: get vault secrets
      ansible.builtin.lineinfile:
        path: ~/app.json
        line: "{{ lookup('hashi_vault', 'secret=expense-{{env}}/data/{{component_name}}  token={{vault_token}} url=https://vault-internal.pdevops72.online:8200 validate_certs=False')}}"
        create: yes

