- name: get secrets
  hosts: localhost
  tasks:
    - name: get vault secrets
      ansible.builtin.lineinfile:
        path: /tmp/secrets
        line: "{{ lookup('hashi_vault', 'secret=common/data/vault  token={{vault_token}} url=https://3.81.88.227:8200 validate_certs=False')}}"
        create: yes

