- name: Install mysql server package
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: start and enable service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Install Python MySQL Client
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
      - pymysql
    executable: pip3.9

- name: Get DB Info credentials
  community.mysql.mysql_info:
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    login_host: 172.31.84.158
    filter: version
  register: mysql_connection_output
#  ignore_errors: true

- name: Receive DB Info
  ansible.builtin.debug:
    msg: "{{mysql_connection_output}}"

- name: Set Root password
  ansible.builtin.shell: mysql_secure_installation --set-{{ login_user }}-pass {{ login_password }}
  when: mysql_connection_output.failed is false

#{{ mysql_root_password }} here mysql_root_password getting the password from vault